global:
  scrape_interval: 10s  
  scrape_timeout: 5s  

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"] 
  
  - job_name: 'my-app'
    static_configs:
      - targets: ['api-opentelemetry:8080']